name: hoover
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.7
  - pip
  - numpy
  - scipy
  - pandas
  - ipython
  - matplotlib
  - emcee
  - pysm3
  - pip:
     # add here only pip-packages that are not available in conda/conda-forge! E.g.:
     - corner
     - jaxlib
     - jax
  # for development only (could also be kept in a separate environment file)
  - jupyterlab
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - sphinx
  - recommonmark
