
dustmbb:
  fixed:
    # reference frequency in GHz
    nu_ref_d: 353.
    # temperature in K
    T_d: 20.
  varied:
    beta_d: [1.5, 0.5]
syncpl:
  fixed:
    nu_ref_s: 23.
  varied:
    beta_s: [-3., 0.1] 
cmb:
  fixed:
  varied: